services:
  zmenu:
    build: .
    container_name: zmenu
    ports:
      - "8088:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - zos-network
      - homelab-net

networks:
  zos-network:
    external: true
  homelab-net:
    external: true
